use_frameworks!

platform :ios, '8.0'

target 'pixlee_api_Example' do
  pod 'pixlee_api', :path => '../'
  
  pod 'Masonry', '~> 1.1'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'FormatterKit', '~> 1.8.2'
  
  target 'pixlee_api_Tests' do
    inherit! :search_paths

    
  end
end
