# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'pixlee_example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'pixlee_api', '~> 1.74'
  
  pod 'Masonry', '~> 1.1'
  pod 'SDWebImage', '~> 3.8.2'
  pod 'FormatterKit', '~> 1.8.2'
  # Pods for pixlee_example

  target 'pixlee_exampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

